services:
    accountingservice:
        image: nkn5729/accounting-service:latest
        container_name: accounting-service
        ports:
            - 6900:6900
        environment:
            DATABASE_URL: jdbc:postgresql://accountingdb:5432/accounting_db
            DATABASE_USERNAME: accountinguser
            DATABASE_PASSWORD: accountingUser_pw_geheim
            SERVICE_PORT: 6900
        depends_on:
            accountingdb:
                condition: service_healthy
            kafka:
                condition: service_started

    accountingdb:
        image: postgres:latest
        container_name: accountingdb
        environment:
            POSTGRES_DB: accounting_db
            POSTGRES_USER: accountinguser
            POSTGRES_PASSWORD: accountingUser_pw_geheim
        ports:
            - '2345:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U accountinguser -d accounting_db']
            interval: 5s
            timeout: 5s
            retries: 5
