services:
  postgres-organization:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '6742:5432'
  organizationservice:
    image: 'swe5076/swe5076:organizationservice_img'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://host.docker.internal:6742/mydatabase'
      - 'kafka.server.url=host.docker.internal:9092'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - kafka
